version: '3.4'

services:
  etraveller.api.accommodations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  etraveller.api.flights:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"


  etraveller.api.travels:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Flights=http://etraveller.api.flights
      - Services__Accommodations=http://etraveller.api.accommodations

    ports:
      - "6003:80"

