version: '3.4'

services:
  etraveller.api.accommodations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  etraveller.api.flights:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  etraveller.api.travels:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

