version: '3.4'

services:
  etraveller.api.accommodations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:8080"

  etraveller.api.flights:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:8080"


  etraveller.api.travels:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:8080"

